### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mvmcjr** [Herocod3r/QrWebCam#1]
Hello first of all congratz on the project, it helped me a lot, but I could not help but notice that there's a memory leak on this code, as for now I could not identify it and it would be awesome of you to try to fix it.

Anyway even if you don't just passing by to notice anyone interested. Thanks anyways dude !

**Comment by Herocod3r** [comment]
Well, this was kind of a rush work, code was written under heavy pressure...i kind of noticed the bug....but you know, once it works....who cares?? *lol*.... if i have time later, i would look into it...or u could just do stuff on it....and i would add it to the project.

**Comment by mvmcjr** [comment]
Yeah I did some changes but it's still not perfect, as soon as I get it fixed I'll send a pull request

**Comment by Herocod3r** [comment]
ok, Thanks!!

**Comment by mvmcjr** [comment]
On visual studio's enviroment it seems to be a memory leak, but in multiple normal machines that I tested, it seems to be fixed.
